version: '2'

services:
  mysql:
    build:
      context: ./docker/mariadb
    image: mariadb:latest
    container_name: mysql-queue
    #command: mysqld --init-file="./docker/mariadb/install_db.sql"
    volumes:
      - mysql-data:/var/lib/mysql
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=testes
      - MYSQL_DATABASE=queue_test
      - MYSQL_USER=sandbox
      - MYSQL_PASSWORD=sandbox
      
      
  redis:
    image: redis:alpine
    container_name: redis-queue
    volumes:
      - redis-data:/data

  php:
    build:
      context: ./docker/php7-fpm
    image: laravel:php-fpm
    container_name: php-queue
    depends_on:
      - redis
      - mysql
    command: bash -c "php-fpm  && php-fpm -v"
    environment:
      DB_PORT: 3306
      DB_USERNAME: root
      DB_DATABASE: queue_test
      DB_PASSWORD: testes
      DB_HOST: mysql
      MYSQL_HOST: mysql
      REDIS_HOST: redis
      QUEUE_DRIVER: redis
      DEBUG: 1
      
    links:
      - mysql
      - redis
    volumes:
      - ./app/:/var/www/html:rw
  queue:
    image: laravel:php-fpm
    depends_on:
      - php
    volumes_from:
      - php
    environment:
      APP_ENV: local
      CONTAINER_ROLE: queue
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
      DB_PORT: 3306
      DB_USERNAME: root
      DB_DATABASE: queue_test
      DB_PASSWORD: testes
      DB_HOST: mysql
      MYSQL_HOST: mysql
    links:
      - redis
  web:
    image: nginx:alpine
    container_name: nginx-queue
    depends_on:
      - php
      - redis
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
    ports:
      - 4001:4001

volumes:
  redis-data:
    driver: "local"
  mysql-data:
    driver: "local"
